Fix error with BusyBox when query is empty
using `awk` from BusyBox v1.27.2, supplied with Android Termux
https://termux.com/

Error is

    regerror: assertion "errbuf != NULL" failed

caused when `q` is empty.